// Slide plan v2 for "No Free Lunch in Income Investing" (Apr 13, 2026)
// Timestamps in seconds. Source video: public/source/episode-2026-04-13-no-free-lunch-1080p24.mp4
// Real monthly return paths come from ./returns-data.json (generated by scripts/fetch-returns.ts)

import returnsData from './returns-data.json' assert { type: 'json' };

export const episodeConfig = {
  title: 'There Is No Free Lunch in Income Investing',
  showTitle: 'The Wealth Strategy Podcast by ArcVest',
  hosts: 'Chad Fargason & Eric Cooper',
  date: 'April 13, 2026',
  sourceVideo: 'source/episode-2026-04-13-no-free-lunch-1080p24.mp4',
  fps: 24,
  widthPx: 1920,
  heightPx: 1080,
  durationSec: 1552.3,
  ctaUrl: 'arcvest.com',
  tagline: 'Pay Less. Keep More.',
  disclaimer:
    'Hypothetical illustrations. Past performance does not guarantee future results. Return figures referenced are approximate 10-year total-return comparisons for commonly referenced ETF proxies (SPY, BIZD, VNQ, AMLP, NOBL), Jan 2016 – Dec 2025. Not a forecast. Not individualized investment advice.',
} as const;

export type SegmentKind = 'video' | 'slide';

export type SlideKind =
  | 'title'
  | 'chapter'
  | 'timeline'
  | 'dual-line'
  | 'scoreboard'
  | 'stat'
  | 'checklist'
  | 'quote'
  | 'concept'
  | 'primer'
  | 'outro';

// Slide kinds where captions at the bottom would visually compete with the on-screen copy.
// For these, captions auto-suppress while the slide is up.
export const CAPTION_SUPPRESSING_KINDS: ReadonlySet<SlideKind> = new Set([
  'title',
  'chapter',
  'concept',
  'quote',
  'primer',
  'outro',
]);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface Segment {
  startSec: number;
  endSec: number;
  kind: SegmentKind;
  slide?: SlideKind;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  props?: Record<string, any>;
  /** Optional: when set on a slide segment, overlay a rounded-rectangle PIP of the source video starting at this frame of the source. */
  pipStartSec?: number;
}

const spy = (returnsData as Record<string, { cumulative: number[] }>).SPY.cumulative;
const bizd = (returnsData as Record<string, { cumulative: number[] }>).BIZD.cumulative;
const vnq = (returnsData as Record<string, { cumulative: number[] }>).VNQ.cumulative;
const amlp = (returnsData as Record<string, { cumulative: number[] }>).AMLP.cumulative;

export const slidePlan: Segment[] = [
  // === Part 1 — Cold open + intro ===
  { startSec: 0, endSec: 27, kind: 'video' },
  {
    startSec: 27,
    endSec: 38,
    kind: 'slide',
    slide: 'title',
    props: {
      showTitle: episodeConfig.showTitle,
      episodeTitle: episodeConfig.title,
      hosts: episodeConfig.hosts,
      date: episodeConfig.date,
    },
  },
  { startSec: 38, endSec: 58, kind: 'video' },

  // Moved from 3:30 to 0:58 per Chad's feedback
  {
    startSec: 58,
    endSec: 75,
    kind: 'slide',
    slide: 'concept',
    props: {
      headline: '9–11% yield.',
      subline: 'No volatility. Semi-liquid. Equity-like upside.',
      footer: 'No free lunch.',
    },
  },
  { startSec: 75, endSec: 102, kind: 'video' },

  // === Part 2 — Scale & primer for private credit ===
  {
    startSec: 102,
    endSec: 120,
    kind: 'slide',
    slide: 'stat',
    props: {
      kicker: 'Private credit market size',
      value: '$2–3T',
      context: 'Up from a few hundred billion to $2–3 trillion in a decade.',
    },
  },
  {
    startSec: 120,
    endSec: 145,
    kind: 'slide',
    slide: 'primer',
    props: {
      kicker: 'Primer',
      heading: 'What is private credit?',
      items: [
        {
          accent: 'Borrow',
          label: 'Mid-sized companies take private loans',
          detail: 'Outside the public bond market. Non-bank lenders step in.',
        },
        {
          accent: 'Lend',
          label: 'Private credit funds make the loans',
          detail: 'Investors pool capital. The fund charges fees. Loans pay interest.',
        },
        {
          accent: 'Earn',
          label: 'Investors collect a yield',
          detail: 'Advertised at 8–11%. Marketed as low-volatility and "semi-liquid."',
        },
      ],
      layout: 'rows',
    },
  },
  { startSec: 145, endSec: 294, kind: 'video' },

  // === Part 3 — SaaS-pocalypse + Gates (PIK toggle slide removed) ===
  {
    startSec: 294,
    endSec: 308,
    kind: 'slide',
    slide: 'chapter',
    props: { kicker: 'Part 2', title: 'The SaaS-pocalypse' },
  },
  { startSec: 308, endSec: 510, kind: 'video' },

  // Shortened 40% per Chad
  {
    startSec: 510,
    endSec: 546,
    kind: 'slide',
    slide: 'timeline',
    props: {
      heading: 'The Unmasking — Feb to Apr 2026',
      events: [
        {
          date: 'Feb 9, 2026',
          title: 'UBS warns: 13% default-rate projection',
          detail: 'AI "liquefying the moats" of legacy SaaS borrowers.',
        },
        {
          date: 'Feb 18, 2026',
          title: 'Blue Owl sells $1.4B in assets',
          detail: 'Shoring up liquidity as quarterly marks come under pressure.',
        },
        {
          date: 'Apr 2, 2026',
          title: 'Blue Owl caps withdrawals',
          detail: '$5.4B Q1 redemption requests. OCIC hit 21.9% of shares.',
        },
        {
          date: 'Apr 6–9, 2026',
          title: 'Gates slam shut industry-wide',
          detail: 'Barings & Ares cap at 5%. Carlyle requests at 15.7% — triple the limit.',
        },
      ],
    },
  },
  {
    startSec: 546,
    endSec: 564,
    kind: 'slide',
    slide: 'stat',
    props: {
      kicker: 'Capital trapped behind the gates',
      value: '$4.6B',
      context: 'Investor capital frozen as of early April 2026.',
      attribution: 'Bloomberg',
      emphasisColor: 'gap',
    },
  },
  { startSec: 564, endSec: 740, kind: 'video' },

  // === Part 4 — Yield vs Return primer ===
  {
    startSec: 740,
    endSec: 765,
    kind: 'slide',
    slide: 'primer',
    props: {
      kicker: 'Primer',
      heading: 'Yield vs Total Return',
      items: [
        {
          accent: 'Yield',
          label: 'Cash paid out',
          detail: 'Dividends and interest. Often taxed as ordinary income.',
        },
        {
          accent: 'Total Return',
          label: 'Everything that happened',
          detail: 'Price change + dividends + interest — reinvested. Every advisor comparison should use this.',
        },
      ],
      layout: 'columns',
    },
  },
  { startSec: 765, endSec: 870, kind: 'video' },

  // === Part 5 — Primer + BDC/REIT/MLP charts + Scoreboard (with real data) ===
  {
    startSec: 870,
    endSec: 895,
    kind: 'slide',
    slide: 'primer',
    props: {
      kicker: 'Primer',
      heading: 'BDCs, REITs, and MLPs',
      items: [
        {
          accent: 'BDC',
          label: 'Business Development Company',
          detail: 'Publicly traded fund that lends to mid-market businesses. Pays a high dividend.',
        },
        {
          accent: 'REIT',
          label: 'Real Estate Investment Trust',
          detail: 'Owns rental property or real-estate debt. Must pay out ~90% of income.',
        },
        {
          accent: 'MLP',
          label: 'Master Limited Partnership',
          detail: 'Energy-infrastructure partnership. Pays "distributions." Tax-complex.',
        },
      ],
      layout: 'rows',
      footerNote: 'Sold as "income plays." Next up: how they actually performed.',
    },
  },
  { startSec: 895, endSec: 927, kind: 'video' },

  {
    startSec: 927,
    endSec: 960,
    kind: 'slide',
    slide: 'dual-line',
    props: {
      heading: 'BDCs vs SPY',
      subheading: 'BIZD (BDC index ETF) · $1 invested, total return · Jan 2016 – Dec 2025',
      winnerLabel: 'SPY',
      winnerEndValue: '$3.95',
      loserLabel: 'BIZD',
      loserEndValue: '$2.47',
      winnerPath: spy,
      loserPath: bizd,
      caveat: 'Same volatility as stocks — with half the return.',
      period: 'Jan 2016 – Dec 2025',
    },
  },
  { startSec: 960, endSec: 1020, kind: 'video' },

  {
    startSec: 1020,
    endSec: 1035,
    kind: 'slide',
    slide: 'dual-line',
    props: {
      heading: 'REITs vs SPY',
      subheading: 'VNQ (broad real-estate ETF) · $1 invested, total return · Jan 2016 – Dec 2025',
      winnerLabel: 'SPY',
      winnerEndValue: '$3.95',
      loserLabel: 'VNQ',
      loserEndValue: '$1.65',
      winnerPath: spy,
      loserPath: vnq,
      caveat: 'Rate-sensitive. Not the safety story it was sold as.',
      period: 'Jan 2016 – Dec 2025',
    },
  },
  { startSec: 1035, endSec: 1160, kind: 'video' },

  {
    startSec: 1160,
    endSec: 1195,
    kind: 'slide',
    slide: 'dual-line',
    props: {
      heading: 'MLPs vs SPY',
      subheading: 'AMLP (MLP index ETF) · $1 invested, total return · Jan 2016 – Dec 2025',
      winnerLabel: 'SPY',
      winnerEndValue: '$3.95',
      loserLabel: 'AMLP',
      loserEndValue: '$1.82',
      winnerPath: spy,
      loserPath: amlp,
      caveat: 'AMLP lost 32% in 2020. Never caught back up.',
      period: 'Jan 2016 – Dec 2025',
    },
  },
  {
    startSec: 1195,
    endSec: 1220,
    kind: 'slide',
    slide: 'scoreboard',
    props: {
      heading: 'The 10-Year Scoreboard',
      subheading: '$1 invested, total return (Jan 2016 – Dec 2025)',
      rows: [
        { label: 'SPY (S&P 500)', value: 3.95, display: '$3.95', isWinner: true },
        { label: 'BIZD (BDCs)', value: 2.47, display: '$2.47' },
        { label: 'AMLP (MLPs)', value: 1.82, display: '$1.82' },
        { label: 'VNQ (REITs)', value: 1.65, display: '$1.65' },
      ],
    },
  },
  { startSec: 1220, endSec: 1280, kind: 'video' },

  // === Part 6 — Aristocrats primer + 80/20 stat ===
  {
    startSec: 1280,
    endSec: 1305,
    kind: 'slide',
    slide: 'primer',
    props: {
      kicker: 'Primer',
      heading: 'What are Dividend Aristocrats?',
      items: [
        {
          accent: 'Definition',
          label: 'S&P 500 companies that raised their dividend every year for 25+ years',
          detail: 'Think Procter & Gamble, Coca-Cola, Johnson & Johnson. ETF proxy: NOBL.',
        },
      ],
      layout: 'rows',
      footerNote: 'Often pitched as the "safe" dividend strategy.',
    },
  },
  { startSec: 1305, endSec: 1328, kind: 'video' },

  {
    startSec: 1328,
    endSec: 1345,
    kind: 'slide',
    slide: 'stat',
    props: {
      kicker: '10-year annualized returns',
      value: '12.0% vs 10.1%',
      context: '80/20 SPY + Treasuries beat the Dividend Aristocrats (NOBL).',
    },
  },
  { startSec: 1345, endSec: 1365, kind: 'video' },

  // Tax drag slide — WITH PIP
  {
    startSec: 1365,
    endSec: 1390,
    kind: 'slide',
    slide: 'concept',
    pipStartSec: 1365,
    props: {
      headline: 'Dividends = tax drag.',
      subline: 'Ordinary income tax on yield you may not even need.',
    },
  },
  { startSec: 1390, endSec: 1400, kind: 'video' },

  // === Part 7 — Minimalist Solution ===
  {
    startSec: 1400,
    endSec: 1415,
    kind: 'slide',
    slide: 'chapter',
    props: { kicker: 'Part 5', title: 'The Minimalist Solution' },
  },
  { startSec: 1415, endSec: 1430, kind: 'video' },

  {
    startSec: 1430,
    endSec: 1488,
    kind: 'slide',
    slide: 'checklist',
    props: {
      heading: 'Own this, full stop.',
      items: [
        {
          title: '70–80% broad risk assets',
          detail: 'S&P 500, total US market, some international + gold for diversification.',
        },
        {
          title: '20–30% in T-bills or short, high-quality bonds',
          detail: 'Triple-B and up. Stability and liquidity — not reaching for yield.',
        },
        {
          title: 'Sell shares when you need cash',
          detail: 'It\'s more tax-efficient than "living off income."',
        },
      ],
    },
  },
  { startSec: 1488, endSec: 1520, kind: 'video' },

  {
    startSec: 1520,
    endSec: 1532,
    kind: 'slide',
    slide: 'quote',
    props: {
      quote: 'Low fees, broadly diversified, sell shares when you need them.',
      attribution: 'Chad Fargason',
    },
  },
  { startSec: 1532, endSec: 1547, kind: 'video' },

  // === Part 8 — Outro ===
  {
    startSec: 1547,
    endSec: 1552,
    kind: 'slide',
    slide: 'outro',
    props: {
      url: episodeConfig.ctaUrl,
      tagline: episodeConfig.tagline,
      disclaimer: episodeConfig.disclaimer,
    },
  },
];
